# Hybridization of multiple Models by Linear Averaging 

In [17]:
import pandas as pd
import numpy as np
import seaborn
import matplotlib.pyplot as plt

df=pd.read_csv("data.csv")
df.head()



age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

# Spliting dependent and independent variable

In [18]:
x= df.iloc[:, 0:13]
y= df.iloc[:, 13].values

# Spliting traning and testing dataset

In [19]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.3, random_state=12)

# Scaling the test data and creating empty lists

In [20]:
from sklearn.preprocessing import StandardScaler
  
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)
print(x_test)

acc=[]
rec=[]
pre=[]
f1 =[]

[[ 0.1586933   0.69162889  0.06797935 ... -2.29561849 -0.75174546
  -0.56822375]
 [-0.91777878 -1.44586211  1.04280319 ... -2.29561849 -0.75174546
  -0.56822375]
 [ 0.80457655 -1.44586211  1.04280319 ... -0.65294538  0.20733193
   1.09470045]
 ...
 [ 1.34281259  0.69162889 -0.90684449 ... -0.65294538  2.12548672
  -0.56822375]
 [ 1.01987097  0.69162889 -0.90684449 ... -0.65294538  0.20733193
   1.09470045]
 [ 0.37398772  0.69162889  1.04280319 ...  0.98972773 -0.75174546
  -0.56822375]]


# Logistic regression

In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
  
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)


y_pred = classifier.predict(x_test)


from sklearn.metrics import confusion_matrix
  
cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix : \n", cm)


from sklearn.metrics import accuracy_score
  
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Recall : ", recall_score(y_test, y_pred))
print ("precision : ", precision_score(y_test, y_pred))
print ("F1_measure: ", f1_score(y_test, y_pred))

acc.append( accuracy_score(y_test, y_pred))
pre.append(precision_score(y_test, y_pred))
rec.append(recall_score(y_test, y_pred))
f1.append(f1_score(y_test , y_pred))






Confusion Matrix : 
 [[115  32]
 [ 22 139]]
Accuracy :  0.8246753246753247
Recall :  0.8633540372670807
precision :  0.8128654970760234
F1_measure:  0.8373493975903614


# KNN witn n=1

In [22]:
from sklearn.neighbors import KNeighborsClassifier

knn5 = KNeighborsClassifier(n_neighbors = 5)
knn1 = KNeighborsClassifier(n_neighbors=1)

knn5.fit(x_train, y_train)
knn1.fit(x_train, y_train)

y_pred_5 = knn5.predict(x_test)
y_pred_1 = knn1.predict(x_test)

cm = confusion_matrix(y_test, y_pred_5)
print ("Confusion Matrix : \n", cm)

cm = confusion_matrix(y_test, y_pred_1)
print ("Confusion Matrix : \n", cm)

from sklearn.metrics import accuracy_score
print("Accuracy with k=5", accuracy_score(y_test, y_pred_5))
print("Accuracy with k=1", accuracy_score(y_test, y_pred_1))
print ("Recall : ", recall_score(y_test, y_pred_1))
print ("precision : ", precision_score(y_test, y_pred_1))
print ("F1_measure: ", f1_score(y_test, y_pred_1))

acc.append( accuracy_score(y_test, y_pred_1))
pre.append(precision_score(y_test, y_pred_1))
rec.append(recall_score(y_test, y_pred_1))
f1.append(f1_score(y_test , y_pred_1))

#k=1 model is selected

Confusion Matrix : 
 [[133  14]
 [ 29 132]]
Confusion Matrix : 
 [[141   6]
 [  0 161]]
Accuracy with k=5 0.8603896103896104
Accuracy with k=1 0.9805194805194806
Recall :  1.0
precision :  0.9640718562874252
F1_measure:  0.9817073170731708


# Random forest

In [23]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(x_train, y_train)
y_pred_rf = rfc.predict(x_test)

cm = confusion_matrix(y_test, y_pred_rf)
print ("Confusion Matrix : \n", cm)

print ("Accuracy : ", accuracy_score(y_test, y_pred_rf))
print ("Recall : ", recall_score(y_test, y_pred_rf))
print ("precision : ", precision_score(y_test, y_pred_rf))
print ("F1_measure: ", f1_score(y_test, y_pred_rf))

acc.append( accuracy_score(y_test, y_pred_rf))
pre.append(precision_score(y_test, y_pred_rf))
rec.append(recall_score(y_test, y_pred_rf))
f1.append(f1_score(y_test , y_pred_rf))

Confusion Matrix : 
 [[143   4]
 [  0 161]]
Accuracy :  0.987012987012987
Recall :  1.0
precision :  0.9757575757575757
F1_measure:  0.9877300613496933


# Support Vector Machine

In [24]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(x_train, y_train)
y_pred_svm = svc.predict(x_test)

cm = confusion_matrix(y_test, y_pred_svm)
print ("Confusion Matrix : \n", cm)

print ("Accuracy : ", accuracy_score(y_test, y_pred_svm))
print ("Recall : ", recall_score(y_test, y_pred_svm))
print ("precision : ", precision_score(y_test, y_pred_svm))
print ("F1_measure: ", f1_score(y_test, y_pred_svm))

acc.append( accuracy_score(y_test, y_pred_svm))
pre.append(precision_score(y_test, y_pred_svm))
rec.append(recall_score(y_test, y_pred_svm))
f1.append(f1_score(y_test , y_pred_svm))

Confusion Matrix : 
 [[134  13]
 [ 15 146]]
Accuracy :  0.9090909090909091
Recall :  0.906832298136646
precision :  0.9182389937106918
F1_measure:  0.9125000000000001


# Naive Bayes

In [25]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train, y_train)
y_pred_nb = gnb.predict(x_test)

cm = confusion_matrix(y_test, y_pred_nb)
print ("Confusion Matrix : \n", cm)

print ("Accuracy : ", accuracy_score(y_test, y_pred_nb))
print ("Recall : ", recall_score(y_test, y_pred_nb))
print ("precision : ", precision_score(y_test, y_pred_nb))
print ("F1_measure: ", f1_score(y_test, y_pred_nb))

acc.append( accuracy_score(y_test, y_pred_nb))
pre.append(precision_score(y_test, y_pred_nb))
rec.append(recall_score(y_test, y_pred_nb))
f1.append(f1_score(y_test , y_pred_nb))

Confusion Matrix : 
 [[108  39]
 [ 34 127]]
Accuracy :  0.762987012987013
Recall :  0.7888198757763976
precision :  0.7650602409638554
F1_measure:  0.7767584097859327


# Decision Tree

In [26]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)
y_pred_dt = dtc.predict(x_test)

cm = confusion_matrix(y_test, y_pred_dt)
print ("Confusion Matrix : \n", cm)

print ("Accuracy : ", accuracy_score(y_test, y_pred_dt))
print ("Recall : ", recall_score(y_test, y_pred_dt))
print ("precision : ", precision_score(y_test, y_pred_dt))
print ("F1_measure: ", f1_score(y_test, y_pred_dt))

acc.append( accuracy_score(y_test, y_pred_dt))
pre.append(precision_score(y_test, y_pred_dt))
rec.append(recall_score(y_test, y_pred_dt))
f1.append(f1_score(y_test , y_pred_dt))

Confusion Matrix : 
 [[143   4]
 [  0 161]]
Accuracy :  0.987012987012987
Recall :  1.0
precision :  0.9757575757575757
F1_measure:  0.9877300613496933


# Hybridisation of model

In [27]:
sum=0
for i in acc:
    sum=sum+i
y_pred_hb=[]
for index in range(0,len(y_test)):
    #print(index)
    x_test_in=x_test[index]
    #print(x_test_in,"\n\n")
    y_test_out=y[index]
    #print("Actual case - ",y_test_out,"\n\n")
    x_test_in=[x_test_in]
    pre=[]
    y_pred_lr = classifier.predict(x_test_in)
    #print("Logistic regresion prediction - ",y_pred_lr)
    pre.append(y_pred_lr)
    y_pred_1 = knn1.predict(x_test_in)
    #print("KNN with n=1 prediction - ",y_pred_1)
    pre.append(y_pred_1)
    y_pred_rf = rfc.predict(x_test_in)
    #print("Random forest prediction - ",y_pred_rf)
    pre.append(y_pred_rf)
    y_pred_svm = svc.predict(x_test_in)
    #print("SVM prediction - ",y_pred_svm)
    pre.append(y_pred_svm)
    y_pred_nb = gnb.predict(x_test_in)
    #print("Naive Bayes prediction - ",y_pred_nb)
    pre.append(y_pred_nb)
    y_pred_dt = dtc.predict(x_test_in)
    #print("Decision tree prediction - ",y_pred_dt)
    pre.append(y_pred_dt)
    #hybrid prediction percentage
    hb=0
    for i in range(0,len(acc)):
        hb=hb+acc[i]*pre[i]
    hb=(hb/sum)*100
    if(hb>=50):
        y_pred_hb.append(1)
    else:
        y_pred_hb.append(0)
print(y_test)
print(y_pred_hb)
cm = confusion_matrix(y_test, y_pred_hb)
print ("Confusion Matrix : \n", cm)
print ("Accuracy : ", accuracy_score(y_test, y_pred_hb))
print ("Recall : ", recall_score(y_test, y_pred_hb))
print ("precision : ", precision_score(y_test, y_pred_hb))
print ("F1_measure: ", f1_score(y_test, y_pred_hb))
acc.append( accuracy_score(y_test, y_pred_hb))
pre.append(precision_score(y_test, y_pred_hb))
rec.append(recall_score(y_test, y_pred_hb))
f1.append(f1_score(y_test , y_pred_hb))

[1 1 0 0 1 0 1 0 0 0 1 0 1 0 0 0 1 0 1 1 0 1 0 0 1 1 0 0 1 0 1 0 0 1 1 0 1
 1 0 1 1 0 1 1 0 1 1 1 1 0 0 1 1 0 1 1 1 1 0 0 0 1 1 1 1 0 0 1 0 1 0 0 1 0
 0 0 1 0 1 0 0 1 1 1 1 0 0 0 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 0 0 0 0 0 1 0 0
 1 0 1 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 1 1 1 1 0 1 1 1 0 1 1 0 1
 0 0 0 0 1 1 1 0 1 1 0 0 1 0 1 1 0 1 0 0 0 1 1 0 1 0 1 0 1 0 1 0 1 1 0 1 0
 0 1 1 1 0 0 0 1 0 0 0 1 0 1 0 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 1 1 1 1 1 1 1
 0 1 0 1 0 1 0 1 1 1 0 0 0 1 1 0 1 1 1 0 0 0 0 1 1 0 0 0 1 0 1 1 1 1 0 0 1
 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0 1 1 1 1 0 1 1 0 1 1 0 1 0 1 0 0 1 1 0 0
 1 0 0 0 1 0 1 0 1 0 1 1]
[1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0